name: Android CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  apk:
    if: github.event_name != 'release'
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TravelMoneyNote_Debug
          path: app/build/outputs/apk/debug
          
  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle
      # 1. Keystore 디코딩 (GitHub Secrets에 저장된 Base64 문자열을 파일로 변환)
      - name: Decode Keystore
        env:
          SIGNING_KEY : ${{ secrets.SIGNING_KEY }}
        run: |
          echo -n $SIGNING_KEY | base64 -di > app/keystore.jks

      # 2. 릴리즈용 AAB 빌드
      # build.gradle에서 환경변수로 키스토어 정보를 읽도록 설정되어 있어야 함
      - name: Build Release AAB
        env:
          KEY_ALIAS: ${{ secrets.ALIAS }}
          PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          bash ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/app/keystore.jks \
            -Pandroid.injected.signing.store.password=$PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$PASSWORD \
            --stacktrace

      - name: Build release APK
        env:
          KEY_ALIAS: ${{ secrets.ALIAS }}
          PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          bash ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/app/keystore.jks \
            -Pandroid.injected.signing.store.password=$PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$PASSWORD \
            --stacktrace
          
      - name: Upload to Release APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/release/app-release.apk
          tag: ${{ github.ref }}
          asset_name: TravelMoneyNote_$tag.apk

      - name: Upload to Release AAB
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/bundle/release/app-release.aab
          tag: ${{ github.ref }}
          asset_name: TravelMoneyNote_$tag.aab
          
      # 구글 플레이는 파일명으로 언어를 구분합니다 (예: whatsnew-ko-KR)
      - name: Create What is New file from Release Notes
        run: |
          mkdir -p distribution/whatsnew
          echo "${{ github.event.release.body }}" > distribution/whatsnew/whatsnew-ko-KR

      # 3. 구글 플레이 콘솔 업로드 (내부 테스트 트랙)
      - name: Upload to Google Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: io.github.mbp16.travelmoneynote
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed # (선택) draft로 올리면 콘솔에서 검토 후 배포 가능, 즉시 배포 원하면 completed
          whatsNewDirectory: distribution/whatsnew # (선택) 변경사항 텍스트 폴더
